name: Backport
on:
  pull_request_target:
    types: ["labeled", "closed"]

jobs:
  backport:
    name: "Backporter"
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
        || (
          github.event.action == 'labeled'
          && contains(github.event.labels.*.name, 'backport')
        )
      )
    steps:
      - run: echo "PR ${{ github.event.number }}, has labels ${{ toJson(github.event.pull_request.labels.*.name) }}"
        name: listing params

